apiVersion: "monitoring.whatap.com/v2alpha1"
kind: "WhatapAgent"
metadata:
  labels:
    app.kubernetes.io/managed-by: "whatap-operator"
    app.kubernetes.io/name: "whatap"
  name: "whatap"
  namespace: "whatap-monitoring"
spec:
  features:
    k8sAgent:
      customAgentImageFullName: "public.ecr.aws/whatap/kube_mon:1.8.7"
      gpuMonitoring:
        enabled: false
      masterAgent:
        enabled: true
      nodeAgent:
        enabled: true
        runtime: "containerd"
        runtimeSocketPath: "/var/run/containerd/containerd.sock"
