apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-was
type: Opaque
stringData:
  db-url: "jdbc:mysql://db-server-pj.mysql.database.azure.com:3306/kbeauty?useSSL=true&serverTimezone=Asia/Seoul"
  db-user: "testuser"
  db-password: "qwert123!"