apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: app-was
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-url
      remoteRef:
        key: kbeauty-db-url
    - secretKey: db-user
      remoteRef:
        key: kbeauty-db-user
    - secretKey: db-password
      remoteRef:
        key: kbeauty-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: app-was
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-host
      remoteRef:
        key: kbeauty-redis-host
    - secretKey: redis-ssl-port
      remoteRef:
        key: kbeauty-redis-ssl-port
    - secretKey: redis-password
      remoteRef:
        key: kbeauty-redis-password
