apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - was-blue-deployment.yaml
  - was-blue-hpa.yaml
  - was-blue-service.yaml
  - was-green-deployment.yaml
  - was-green-hpa.yaml
  - was-service.yaml
  - was-green-service.yaml
