apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: "<tenant-id>"
      vaultUrl: "<key-vault-url>"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets