license=x6063d0838jo5-zo3fc1dr76nss-x2fargoqq3nmrs
whatap.server.host=13.124.11.223/13.209.172.35

tx_caller_meter_enabled=true
sql_dbc_meter_enabled=true
httpc_host_meter_enabled=true
actx_meter_enabled=true

#로그모니터링
logsink_enabled=true