apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whatap-credentials
  namespace: whatap-monitoring
  annotations:
    argocd.argoproj.io/tracking-id: final-pj-whatap:external-secrets.io/ExternalSecret:whatap-monitoring/whatap-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: whatap-credentials
    creationPolicy: Owner
  data:
    - secretKey: WHATAP_LICENSE
      remoteRef:
        key: kbeauty-whatap-license
    - secretKey: WHATAP_HOST
      remoteRef:
        key: kbeauty-whatap-host
    - secretKey: WHATAP_PORT
      remoteRef:
        key: kbeauty-whatap-port