services:
  was:
    build:
      context: ../../../..
      dockerfile: k8s/was/image_build/blue/Dockerfile
      #args:
        #APP_DIR: app/was_blue
        #WHATAP_DIR: whatap
    image: final-pj-was-blue:latest
    container_name: final-pj-was-blue
    #environment:
      #WHATAP_AGENT_PATH: /whatap/whatap.agent-2.2.75.jar
      #WHATAP_ONAME: monitoring-blue
    ports:
      - "8080:8080"
    restart: unless-stopped